### PR TITLE
Client: handle exceptions related to Redis

### LINKED ISSUE #10: Client: handle exceptions related to Redis
```
hubot-rocketchat_1  | [ioredis] Unhandled error event: ReplyError: ERR invalid password
hubot-rocketchat_1  |   at parseError (/home/hubot/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12)
hubot-rocketchat_1  |   at parseType (/home/hubot/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14)
```

### PR DESCRIPTION
**Pull request by ya7on**
close #10

### CODE REVIEW

File: client/huntflow-reloaded.js [hunk 1]
```diff
@@ -16,29 +16,31 @@ module.exports = async (robot) => {
...
   }
 
-  let connected = false
-
-  for (let i = 0; i < attemptsNumber; i++) {
-    if (redis.status === 'ready') {
-      connected = true
-      break
-    }
+  redis.on('end', () => console.log('Redis connection is closed'))
```
Comment (eugulixes) [inline client/huntflow-reloaded.js]: Let's use here `robot.logger.info`

File: client/huntflow-reloaded.js [hunk 2]
```diff
@@ -16,29 +16,31 @@ module.exports = async (robot) => {
...
 
-    await routines.delay(1000)
-  }
+  redis.on('reconnecting', time => console.log(`Could not connect to Redis. Retying after ${time}ms...`))
```
Comment (eugulixes) [inline client/huntflow-reloaded.js]: `robot.logger.info`

File: client/huntflow-reloaded.js [hunk 3]
```diff
@@ -16,29 +16,31 @@ module.exports = async (robot) => {
...
 
-  if (!connected) {
-    routines.rave(robot, `Could not connect to Redis`)
-    return
-  }
+  redis.on('error', (err) => {
+    // Some of error codes are no need to print here.
```
Comment (eugulixes) [inline client/huntflow-reloaded.js]:
```
There is no need to print here some of the error codes.
```

**Review by eugulixes — APPROVED** [review]
